name: Run Dependabot on Demand

on:
  workflow_dispatch:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dependabot Updates
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -X POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/dependabot/updates \
            --silent
